/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uAEPi88t4b3bpYVaXpTdTs

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsrrte2NAt5PWz } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: RRTE2nAt5PWz/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsrrte2NAt5PWz
});
