/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uAEPi88t4b3bpYVaXpTdTs
// Component: 7znckC74KvDx

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HeaderNav from "../../HeaderNav"; // plasmic-import: WF8M3r6EBNxf/component
import Button from "../../Button"; // plasmic-import: z_xtdmApUYx9/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uAEPi88t4b3bpYVaXpTdTs/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uAEPi88t4b3bpYVaXpTdTs/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicSignup.module.css"; // plasmic-import: 7znckC74KvDx/css

import Mail2Icon from "./icons/PlasmicIcon__Mail2"; // plasmic-import: -TEK5tkAaHwU/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: LmWEQWz3GDM0/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: 8FhjggOMKijk/icon
import SocialIcon3Icon from "./icons/PlasmicIcon__SocialIcon3"; // plasmic-import: M_WN2o6i_M8F/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicSignup__VariantMembers = {};
export type PlasmicSignup__VariantsArgs = {};
type VariantPropType = keyof PlasmicSignup__VariantsArgs;
export const PlasmicSignup__VariantProps = new Array<VariantPropType>();

export type PlasmicSignup__ArgsType = {};
type ArgPropType = keyof PlasmicSignup__ArgsType;
export const PlasmicSignup__ArgProps = new Array<ArgPropType>();

export type PlasmicSignup__OverridesType = {
  root?: Flex__<"div">;
  body?: Flex__<"div">;
  headerNav?: Flex__<typeof HeaderNav>;
  signUp?: Flex__<"div">;
  content?: Flex__<"div">;
  header?: Flex__<"div">;
  textAndSupportingText?: Flex__<"div">;
  text?: Flex__<"div">;
  supportingText?: Flex__<"div">;
  content3?: Flex__<"div">;
  form?: Flex__<"div">;
  inputField?: Flex__<"div">;
  inputFieldBase?: Flex__<"div">;
  inputWithLabel?: Flex__<"div">;
  label?: Flex__<"div">;
  input?: Flex__<"div">;
  content4?: Flex__<"div">;
  text2?: Flex__<"div">;
  helpIcon?: Flex__<"div">;
  hintText?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  contentDivider?: Flex__<"div">;
  divider?: Flex__<"div">;
  text4?: Flex__<"div">;
  divider2?: Flex__<"div">;
  socialButtonGroup?: Flex__<"div">;
  socialButton?: Flex__<"div">;
  text5?: Flex__<"div">;
  socialButton2?: Flex__<"div">;
  text6?: Flex__<"div">;
  socialButton3?: Flex__<"div">;
  text7?: Flex__<"div">;
  socialButton4?: Flex__<"div">;
  text8?: Flex__<"div">;
  row?: Flex__<"div">;
  text9?: Flex__<"div">;
  buttonsButton2?: Flex__<"div">;
  buttonBase2?: Flex__<"div">;
  text10?: Flex__<"div">;
};

export interface DefaultSignupProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSignup__RenderFunc(props: {
  variants: PlasmicSignup__VariantsArgs;
  args: PlasmicSignup__ArgsType;
  overrides: PlasmicSignup__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_uAEPi88t4b3bpYVaXpTdTs",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"body"}
            data-plasmic-override={overrides.body}
            className={classNames("all", sty.body)}
          >
            <HeaderNav
              data-plasmic-name={"headerNav"}
              data-plasmic-override={overrides.headerNav}
              className={classNames("__wab_instance", sty.headerNav)}
            />

            <div
              data-plasmic-name={"signUp"}
              data-plasmic-override={overrides.signUp}
              className={classNames("all", sty.signUp)}
            >
              <div
                data-plasmic-name={"content"}
                data-plasmic-override={overrides.content}
                className={classNames("all", sty.content)}
              >
                <div
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                  className={classNames("all", sty.header)}
                >
                  <div
                    data-plasmic-name={"textAndSupportingText"}
                    data-plasmic-override={overrides.textAndSupportingText}
                    className={classNames("all", sty.textAndSupportingText)}
                  >
                    <div
                      data-plasmic-name={"text"}
                      data-plasmic-override={overrides.text}
                      className={classNames("all", "__wab_text", sty.text)}
                    >
                      {"Create an account"}
                    </div>
                    <div
                      data-plasmic-name={"supportingText"}
                      data-plasmic-override={overrides.supportingText}
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.supportingText
                      )}
                    >
                      {"Start your 30-day free trial."}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"content3"}
                  data-plasmic-override={overrides.content3}
                  className={classNames("all", sty.content3)}
                >
                  <div
                    data-plasmic-name={"form"}
                    data-plasmic-override={overrides.form}
                    className={classNames("all", sty.form)}
                  >
                    <div
                      data-plasmic-name={"inputField"}
                      data-plasmic-override={overrides.inputField}
                      className={classNames("all", sty.inputField)}
                    >
                      <div
                        data-plasmic-name={"inputFieldBase"}
                        data-plasmic-override={overrides.inputFieldBase}
                        className={classNames("all", sty.inputFieldBase)}
                      >
                        <div
                          data-plasmic-name={"inputWithLabel"}
                          data-plasmic-override={overrides.inputWithLabel}
                          className={classNames("all", sty.inputWithLabel)}
                        >
                          {false ? (
                            <div
                              data-plasmic-name={"label"}
                              data-plasmic-override={overrides.label}
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.label
                              )}
                            >
                              {"Email"}
                            </div>
                          ) : null}
                          <div
                            data-plasmic-name={"input"}
                            data-plasmic-override={overrides.input}
                            className={classNames("all", sty.input)}
                          >
                            <div
                              data-plasmic-name={"content4"}
                              data-plasmic-override={overrides.content4}
                              className={classNames("all", sty.content4)}
                            >
                              {false ? (
                                <Mail2Icon
                                  className={classNames("all", sty.svg__xAw5P)}
                                  role={"img"}
                                />
                              ) : null}
                              <div
                                data-plasmic-name={"text2"}
                                data-plasmic-override={overrides.text2}
                                className={classNames(
                                  "all",
                                  "__wab_text",
                                  sty.text2
                                )}
                              >
                                {"Enter your email"}
                              </div>
                            </div>
                            {false ? (
                              <div
                                data-plasmic-name={"helpIcon"}
                                data-plasmic-override={overrides.helpIcon}
                                className={classNames("all", sty.helpIcon)}
                              >
                                <PlasmicImg__
                                  alt={""}
                                  className={classNames(sty.img___9Wlb3)}
                                  displayHeight={"16px"}
                                  displayMaxHeight={"none"}
                                  displayMaxWidth={"100%"}
                                  displayMinHeight={"0"}
                                  displayMinWidth={"0"}
                                  displayWidth={"16px"}
                                  loading={"lazy"}
                                  src={{
                                    src: "/plasmic/tbxhub_new_landing_saas/images/helpCircle.svg",
                                    fullWidth: 16,
                                    fullHeight: 16,
                                    aspectRatio: undefined
                                  }}
                                />
                              </div>
                            ) : null}
                          </div>
                        </div>
                        {false ? (
                          <div
                            data-plasmic-name={"hintText"}
                            data-plasmic-override={overrides.hintText}
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.hintText
                            )}
                          >
                            {"This is a hint text to help user."}
                          </div>
                        ) : null}
                      </div>
                    </div>
                    <Button
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      className={classNames("__wab_instance", sty.button)}
                      color={"neutral"}
                      label={
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__jpdw
                          )}
                        >
                          {"Get Started"}
                        </div>
                      }
                      size={"extraLarge"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"contentDivider"}
                    data-plasmic-override={overrides.contentDivider}
                    className={classNames("all", sty.contentDivider)}
                  >
                    <div
                      data-plasmic-name={"divider"}
                      data-plasmic-override={overrides.divider}
                      className={classNames("all", sty.divider)}
                    />

                    <div
                      data-plasmic-name={"text4"}
                      data-plasmic-override={overrides.text4}
                      className={classNames("all", "__wab_text", sty.text4)}
                    >
                      {"OR"}
                    </div>
                    <div
                      data-plasmic-name={"divider2"}
                      data-plasmic-override={overrides.divider2}
                      className={classNames("all", sty.divider2)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"socialButtonGroup"}
                    data-plasmic-override={overrides.socialButtonGroup}
                    className={classNames("all", sty.socialButtonGroup)}
                  >
                    <div
                      data-plasmic-name={"socialButton"}
                      data-plasmic-override={overrides.socialButton}
                      className={classNames("all", sty.socialButton)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__dlEAf)}
                        displayHeight={"20px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tbxhub_new_landing_saas/images/socialIcon.svg",
                          fullWidth: 20,
                          fullHeight: 20,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        data-plasmic-name={"text5"}
                        data-plasmic-override={overrides.text5}
                        className={classNames("all", "__wab_text", sty.text5)}
                      >
                        {"Sign up with Google"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"socialButton2"}
                      data-plasmic-override={overrides.socialButton2}
                      className={classNames("all", sty.socialButton2)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___544Gz)}
                        displayHeight={"20px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tbxhub_new_landing_saas/images/socialIcon2.svg",
                          fullWidth: 20,
                          fullHeight: 20,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        data-plasmic-name={"text6"}
                        data-plasmic-override={overrides.text6}
                        className={classNames("all", "__wab_text", sty.text6)}
                      >
                        {"Sign up with Facebook"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"socialButton3"}
                      data-plasmic-override={overrides.socialButton3}
                      className={classNames("all", sty.socialButton3)}
                    >
                      <SocialIcon3Icon
                        className={classNames("all", sty.svg__dmKxd)}
                        role={"img"}
                      />

                      <div
                        data-plasmic-name={"text7"}
                        data-plasmic-override={overrides.text7}
                        className={classNames("all", "__wab_text", sty.text7)}
                      >
                        {"Sign up with Apple"}
                      </div>
                    </div>
                    {false ? (
                      <div
                        data-plasmic-name={"socialButton4"}
                        data-plasmic-override={overrides.socialButton4}
                        className={classNames("all", sty.socialButton4)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__b9Jie)}
                          displayHeight={"20px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"20px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/tbxhub_new_landing_saas/images/socialIcon4.svg",
                            fullWidth: 20,
                            fullHeight: 20,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          data-plasmic-name={"text8"}
                          data-plasmic-override={overrides.text8}
                          className={classNames("all", "__wab_text", sty.text8)}
                        >
                          {"Sign in with X"}
                        </div>
                      </div>
                    ) : null}
                  </div>
                </div>
                <div
                  data-plasmic-name={"row"}
                  data-plasmic-override={overrides.row}
                  className={classNames("all", sty.row)}
                >
                  <div
                    data-plasmic-name={"text9"}
                    data-plasmic-override={overrides.text9}
                    className={classNames("all", "__wab_text", sty.text9)}
                  >
                    {"Already have an account?"}
                  </div>
                  <div
                    data-plasmic-name={"buttonsButton2"}
                    data-plasmic-override={overrides.buttonsButton2}
                    className={classNames("all", sty.buttonsButton2)}
                  >
                    <div
                      data-plasmic-name={"buttonBase2"}
                      data-plasmic-override={overrides.buttonBase2}
                      className={classNames("all", sty.buttonBase2)}
                    >
                      <div
                        data-plasmic-name={"text10"}
                        data-plasmic-override={overrides.text10}
                        className={classNames("all", "__wab_text", sty.text10)}
                      >
                        {"Log in"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "body",
    "headerNav",
    "signUp",
    "content",
    "header",
    "textAndSupportingText",
    "text",
    "supportingText",
    "content3",
    "form",
    "inputField",
    "inputFieldBase",
    "inputWithLabel",
    "label",
    "input",
    "content4",
    "text2",
    "helpIcon",
    "hintText",
    "button",
    "contentDivider",
    "divider",
    "text4",
    "divider2",
    "socialButtonGroup",
    "socialButton",
    "text5",
    "socialButton2",
    "text6",
    "socialButton3",
    "text7",
    "socialButton4",
    "text8",
    "row",
    "text9",
    "buttonsButton2",
    "buttonBase2",
    "text10"
  ],
  body: [
    "body",
    "headerNav",
    "signUp",
    "content",
    "header",
    "textAndSupportingText",
    "text",
    "supportingText",
    "content3",
    "form",
    "inputField",
    "inputFieldBase",
    "inputWithLabel",
    "label",
    "input",
    "content4",
    "text2",
    "helpIcon",
    "hintText",
    "button",
    "contentDivider",
    "divider",
    "text4",
    "divider2",
    "socialButtonGroup",
    "socialButton",
    "text5",
    "socialButton2",
    "text6",
    "socialButton3",
    "text7",
    "socialButton4",
    "text8",
    "row",
    "text9",
    "buttonsButton2",
    "buttonBase2",
    "text10"
  ],
  headerNav: ["headerNav"],
  signUp: [
    "signUp",
    "content",
    "header",
    "textAndSupportingText",
    "text",
    "supportingText",
    "content3",
    "form",
    "inputField",
    "inputFieldBase",
    "inputWithLabel",
    "label",
    "input",
    "content4",
    "text2",
    "helpIcon",
    "hintText",
    "button",
    "contentDivider",
    "divider",
    "text4",
    "divider2",
    "socialButtonGroup",
    "socialButton",
    "text5",
    "socialButton2",
    "text6",
    "socialButton3",
    "text7",
    "socialButton4",
    "text8",
    "row",
    "text9",
    "buttonsButton2",
    "buttonBase2",
    "text10"
  ],
  content: [
    "content",
    "header",
    "textAndSupportingText",
    "text",
    "supportingText",
    "content3",
    "form",
    "inputField",
    "inputFieldBase",
    "inputWithLabel",
    "label",
    "input",
    "content4",
    "text2",
    "helpIcon",
    "hintText",
    "button",
    "contentDivider",
    "divider",
    "text4",
    "divider2",
    "socialButtonGroup",
    "socialButton",
    "text5",
    "socialButton2",
    "text6",
    "socialButton3",
    "text7",
    "socialButton4",
    "text8",
    "row",
    "text9",
    "buttonsButton2",
    "buttonBase2",
    "text10"
  ],
  header: ["header", "textAndSupportingText", "text", "supportingText"],
  textAndSupportingText: ["textAndSupportingText", "text", "supportingText"],
  text: ["text"],
  supportingText: ["supportingText"],
  content3: [
    "content3",
    "form",
    "inputField",
    "inputFieldBase",
    "inputWithLabel",
    "label",
    "input",
    "content4",
    "text2",
    "helpIcon",
    "hintText",
    "button",
    "contentDivider",
    "divider",
    "text4",
    "divider2",
    "socialButtonGroup",
    "socialButton",
    "text5",
    "socialButton2",
    "text6",
    "socialButton3",
    "text7",
    "socialButton4",
    "text8"
  ],
  form: [
    "form",
    "inputField",
    "inputFieldBase",
    "inputWithLabel",
    "label",
    "input",
    "content4",
    "text2",
    "helpIcon",
    "hintText",
    "button"
  ],
  inputField: [
    "inputField",
    "inputFieldBase",
    "inputWithLabel",
    "label",
    "input",
    "content4",
    "text2",
    "helpIcon",
    "hintText"
  ],
  inputFieldBase: [
    "inputFieldBase",
    "inputWithLabel",
    "label",
    "input",
    "content4",
    "text2",
    "helpIcon",
    "hintText"
  ],
  inputWithLabel: [
    "inputWithLabel",
    "label",
    "input",
    "content4",
    "text2",
    "helpIcon"
  ],
  label: ["label"],
  input: ["input", "content4", "text2", "helpIcon"],
  content4: ["content4", "text2"],
  text2: ["text2"],
  helpIcon: ["helpIcon"],
  hintText: ["hintText"],
  button: ["button"],
  contentDivider: ["contentDivider", "divider", "text4", "divider2"],
  divider: ["divider"],
  text4: ["text4"],
  divider2: ["divider2"],
  socialButtonGroup: [
    "socialButtonGroup",
    "socialButton",
    "text5",
    "socialButton2",
    "text6",
    "socialButton3",
    "text7",
    "socialButton4",
    "text8"
  ],
  socialButton: ["socialButton", "text5"],
  text5: ["text5"],
  socialButton2: ["socialButton2", "text6"],
  text6: ["text6"],
  socialButton3: ["socialButton3", "text7"],
  text7: ["text7"],
  socialButton4: ["socialButton4", "text8"],
  text8: ["text8"],
  row: ["row", "text9", "buttonsButton2", "buttonBase2", "text10"],
  text9: ["text9"],
  buttonsButton2: ["buttonsButton2", "buttonBase2", "text10"],
  buttonBase2: ["buttonBase2", "text10"],
  text10: ["text10"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  body: "div";
  headerNav: typeof HeaderNav;
  signUp: "div";
  content: "div";
  header: "div";
  textAndSupportingText: "div";
  text: "div";
  supportingText: "div";
  content3: "div";
  form: "div";
  inputField: "div";
  inputFieldBase: "div";
  inputWithLabel: "div";
  label: "div";
  input: "div";
  content4: "div";
  text2: "div";
  helpIcon: "div";
  hintText: "div";
  button: typeof Button;
  contentDivider: "div";
  divider: "div";
  text4: "div";
  divider2: "div";
  socialButtonGroup: "div";
  socialButton: "div";
  text5: "div";
  socialButton2: "div";
  text6: "div";
  socialButton3: "div";
  text7: "div";
  socialButton4: "div";
  text8: "div";
  row: "div";
  text9: "div";
  buttonsButton2: "div";
  buttonBase2: "div";
  text10: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSignup__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSignup__VariantsArgs;
    args?: PlasmicSignup__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSignup__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSignup__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSignup__ArgProps,
          internalVariantPropNames: PlasmicSignup__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSignup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignup";
  } else {
    func.displayName = `PlasmicSignup.${nodeName}`;
  }
  return func;
}

export const PlasmicSignup = Object.assign(
  // Top-level PlasmicSignup renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    body: makeNodeComponent("body"),
    headerNav: makeNodeComponent("headerNav"),
    signUp: makeNodeComponent("signUp"),
    content: makeNodeComponent("content"),
    header: makeNodeComponent("header"),
    textAndSupportingText: makeNodeComponent("textAndSupportingText"),
    text: makeNodeComponent("text"),
    supportingText: makeNodeComponent("supportingText"),
    content3: makeNodeComponent("content3"),
    form: makeNodeComponent("form"),
    inputField: makeNodeComponent("inputField"),
    inputFieldBase: makeNodeComponent("inputFieldBase"),
    inputWithLabel: makeNodeComponent("inputWithLabel"),
    label: makeNodeComponent("label"),
    input: makeNodeComponent("input"),
    content4: makeNodeComponent("content4"),
    text2: makeNodeComponent("text2"),
    helpIcon: makeNodeComponent("helpIcon"),
    hintText: makeNodeComponent("hintText"),
    button: makeNodeComponent("button"),
    contentDivider: makeNodeComponent("contentDivider"),
    divider: makeNodeComponent("divider"),
    text4: makeNodeComponent("text4"),
    divider2: makeNodeComponent("divider2"),
    socialButtonGroup: makeNodeComponent("socialButtonGroup"),
    socialButton: makeNodeComponent("socialButton"),
    text5: makeNodeComponent("text5"),
    socialButton2: makeNodeComponent("socialButton2"),
    text6: makeNodeComponent("text6"),
    socialButton3: makeNodeComponent("socialButton3"),
    text7: makeNodeComponent("text7"),
    socialButton4: makeNodeComponent("socialButton4"),
    text8: makeNodeComponent("text8"),
    row: makeNodeComponent("row"),
    text9: makeNodeComponent("text9"),
    buttonsButton2: makeNodeComponent("buttonsButton2"),
    buttonBase2: makeNodeComponent("buttonBase2"),
    text10: makeNodeComponent("text10"),

    // Metadata about props expected for PlasmicSignup
    internalVariantProps: PlasmicSignup__VariantProps,
    internalArgProps: PlasmicSignup__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/sign-up",
      pagePath: "/sign-up",
      params: {},
      query: {}
    })
  }
);

export default PlasmicSignup;
/* prettier-ignore-end */
