/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uAEPi88t4b3bpYVaXpTdTs
// Component: WF8M3r6EBNxf

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: z_xtdmApUYx9/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uAEPi88t4b3bpYVaXpTdTs/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uAEPi88t4b3bpYVaXpTdTs/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicHeaderNav.module.css"; // plasmic-import: WF8M3r6EBNxf/css

import HorizontalLogo22SvgIcon from "./icons/PlasmicIcon__HorizontalLogo22Svg"; // plasmic-import: FYLniLePjA4H/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: LmWEQWz3GDM0/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: 8FhjggOMKijk/icon
import ListSvgIcon from "./icons/PlasmicIcon__ListSvg"; // plasmic-import: lwdCMn6YukOq/icon

createPlasmicElementProxy;

export type PlasmicHeaderNav__VariantMembers = {};
export type PlasmicHeaderNav__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeaderNav__VariantsArgs;
export const PlasmicHeaderNav__VariantProps = new Array<VariantPropType>();

export type PlasmicHeaderNav__ArgsType = {};
type ArgPropType = keyof PlasmicHeaderNav__ArgsType;
export const PlasmicHeaderNav__ArgProps = new Array<ArgPropType>();

export type PlasmicHeaderNav__OverridesType = {
  nav?: Flex__<"div">;
  button?: Flex__<typeof Button>;
};

export interface DefaultHeaderNavProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHeaderNav__RenderFunc(props: {
  variants: PlasmicHeaderNav__VariantsArgs;
  args: PlasmicHeaderNav__ArgsType;
  overrides: PlasmicHeaderNav__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"nav"}
      data-plasmic-override={overrides.nav}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_uAEPi88t4b3bpYVaXpTdTs",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.nav
      )}
    >
      <HorizontalLogo22SvgIcon
        className={classNames("all", sty.svg__aEnzG)}
        role={"img"}
      />

      <div className={classNames("all", sty.freeBox___4MrFt)}>
        <PlasmicLink__
          className={classNames("all", "a", "a__uAEPi", sty.link__pqi5S)}
          component={Link}
          legacyBehavior={false}
          platform={"nextjs"}
        >
          <div className={classNames("all", "__wab_text", sty.text__pkWLx)}>
            {"Features"}
          </div>
        </PlasmicLink__>
        <PlasmicLink__
          className={classNames("all", "a", "a__uAEPi", sty.link__ggxd4)}
          component={Link}
          legacyBehavior={false}
          platform={"nextjs"}
        >
          <div className={classNames("all", "__wab_text", sty.text__yo5Wb)}>
            {"Pricing"}
          </div>
        </PlasmicLink__>
        <PlasmicLink__
          className={classNames("all", "a", "a__uAEPi", sty.link__uczS)}
          component={Link}
          legacyBehavior={false}
          platform={"nextjs"}
        >
          <div className={classNames("all", "__wab_text", sty.text___2Y1U0)}>
            {"Integrations"}
          </div>
        </PlasmicLink__>
        <PlasmicLink__
          className={classNames("all", "a", "a__uAEPi", sty.link__ako6T)}
          component={Link}
          legacyBehavior={false}
          platform={"nextjs"}
        >
          <div className={classNames("all", "__wab_text", sty.text__eWcfh)}>
            {"Add-ons"}
          </div>
        </PlasmicLink__>
        <PlasmicLink__
          className={classNames("all", "a", "a__uAEPi", sty.link__foXcE)}
          component={Link}
          legacyBehavior={false}
          platform={"nextjs"}
        >
          <div className={classNames("all", "__wab_text", sty.text__ieFTn)}>
            {"FAQs"}
          </div>
        </PlasmicLink__>
      </div>
      <div className={classNames("all", sty.freeBox__rgmUw)}>
        <PlasmicLink__
          className={classNames("all", "a", "a__uAEPi", sty.link__vWkf1)}
          component={Link}
          legacyBehavior={false}
          platform={"nextjs"}
        >
          <div className={classNames("all", "__wab_text", sty.text__acba7)}>
            {"Login"}
          </div>
        </PlasmicLink__>
        <Button
          data-plasmic-name={"button"}
          data-plasmic-override={overrides.button}
          className={classNames("__wab_instance", sty.button)}
          color={"neutral"}
          label={
            <div className={classNames("all", "__wab_text", sty.text__lca0F)}>
              {"Start for free"}
            </div>
          }
          size={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? "extraSmall"
              : "large"
          }
        />

        <ListSvgIcon
          className={classNames("all", sty.svg__kEYa)}
          role={"img"}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  nav: ["nav", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  nav: "div";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeaderNav__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeaderNav__VariantsArgs;
    args?: PlasmicHeaderNav__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHeaderNav__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHeaderNav__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHeaderNav__ArgProps,
          internalVariantPropNames: PlasmicHeaderNav__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeaderNav__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "nav") {
    func.displayName = "PlasmicHeaderNav";
  } else {
    func.displayName = `PlasmicHeaderNav.${nodeName}`;
  }
  return func;
}

export const PlasmicHeaderNav = Object.assign(
  // Top-level PlasmicHeaderNav renders the root element
  makeNodeComponent("nav"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicHeaderNav
    internalVariantProps: PlasmicHeaderNav__VariantProps,
    internalArgProps: PlasmicHeaderNav__ArgProps
  }
);

export default PlasmicHeaderNav;
/* prettier-ignore-end */
