/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uAEPi88t4b3bpYVaXpTdTs
// Component: 4FD1DbfgGI8F

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HeaderNav from "../../HeaderNav"; // plasmic-import: WF8M3r6EBNxf/component
import Checkbox from "../../Checkbox"; // plasmic-import: KBWpqfAgH2ZW/component
import Button from "../../Button"; // plasmic-import: z_xtdmApUYx9/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uAEPi88t4b3bpYVaXpTdTs/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uAEPi88t4b3bpYVaXpTdTs/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicLogin.module.css"; // plasmic-import: 4FD1DbfgGI8F/css

import Mail2Icon from "./icons/PlasmicIcon__Mail2"; // plasmic-import: -TEK5tkAaHwU/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: LmWEQWz3GDM0/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: 8FhjggOMKijk/icon
import SocialIcon3Icon from "./icons/PlasmicIcon__SocialIcon3"; // plasmic-import: M_WN2o6i_M8F/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicLogin__VariantMembers = {};
export type PlasmicLogin__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogin__VariantsArgs;
export const PlasmicLogin__VariantProps = new Array<VariantPropType>();

export type PlasmicLogin__ArgsType = {};
type ArgPropType = keyof PlasmicLogin__ArgsType;
export const PlasmicLogin__ArgProps = new Array<ArgPropType>();

export type PlasmicLogin__OverridesType = {
  root?: Flex__<"div">;
  body?: Flex__<"div">;
  headerNav?: Flex__<typeof HeaderNav>;
  signUp?: Flex__<"div">;
  content6?: Flex__<"div">;
  header2?: Flex__<"div">;
  textAndSupportingText2?: Flex__<"div">;
  text12?: Flex__<"div">;
  supportingText2?: Flex__<"div">;
  content7?: Flex__<"div">;
  form2?: Flex__<"div">;
  inputField3?: Flex__<"div">;
  inputFieldBase3?: Flex__<"div">;
  inputWithLabel3?: Flex__<"div">;
  label3?: Flex__<"div">;
  input3?: Flex__<"div">;
  content8?: Flex__<"div">;
  text13?: Flex__<"div">;
  helpIcon3?: Flex__<"div">;
  hintText3?: Flex__<"div">;
  inputField2?: Flex__<"div">;
  inputFieldBase2?: Flex__<"div">;
  inputWithLabel2?: Flex__<"div">;
  label2?: Flex__<"div">;
  input2?: Flex__<"div">;
  content5?: Flex__<"div">;
  text3?: Flex__<"div">;
  helpIcon2?: Flex__<"div">;
  hintText2?: Flex__<"div">;
  row3?: Flex__<"div">;
  checkbox?: Flex__<typeof Checkbox>;
  buttonsButton?: Flex__<"div">;
  buttonBase?: Flex__<"div">;
  text14?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  text?: Flex__<"div">;
  actions?: Flex__<"div">;
  socialButtonGroup2?: Flex__<"div">;
  socialButton5?: Flex__<"div">;
  text16?: Flex__<"div">;
  socialButton6?: Flex__<"div">;
  text17?: Flex__<"div">;
  socialButton7?: Flex__<"div">;
  text18?: Flex__<"div">;
  socialButton8?: Flex__<"div">;
  text19?: Flex__<"div">;
  row2?: Flex__<"div">;
  text20?: Flex__<"div">;
  buttonsButton3?: Flex__<"div">;
  buttonBase3?: Flex__<"div">;
  text11?: Flex__<"div">;
};

export interface DefaultLoginProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogin__RenderFunc(props: {
  variants: PlasmicLogin__VariantsArgs;
  args: PlasmicLogin__ArgsType;
  overrides: PlasmicLogin__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "checkbox.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_uAEPi88t4b3bpYVaXpTdTs",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"body"}
            data-plasmic-override={overrides.body}
            className={classNames("all", sty.body)}
          >
            <HeaderNav
              data-plasmic-name={"headerNav"}
              data-plasmic-override={overrides.headerNav}
              className={classNames("__wab_instance", sty.headerNav)}
            />

            <div
              data-plasmic-name={"signUp"}
              data-plasmic-override={overrides.signUp}
              className={classNames("all", sty.signUp)}
            >
              <div
                data-plasmic-name={"content6"}
                data-plasmic-override={overrides.content6}
                className={classNames("all", sty.content6)}
              >
                <div
                  data-plasmic-name={"header2"}
                  data-plasmic-override={overrides.header2}
                  className={classNames("all", sty.header2)}
                >
                  <div
                    data-plasmic-name={"textAndSupportingText2"}
                    data-plasmic-override={overrides.textAndSupportingText2}
                    className={classNames("all", sty.textAndSupportingText2)}
                  >
                    <div
                      data-plasmic-name={"text12"}
                      data-plasmic-override={overrides.text12}
                      className={classNames("all", "__wab_text", sty.text12)}
                    >
                      {"Log in to your account"}
                    </div>
                    <div
                      data-plasmic-name={"supportingText2"}
                      data-plasmic-override={overrides.supportingText2}
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.supportingText2
                      )}
                    >
                      {"Welcome back! Please enter your details."}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"content7"}
                  data-plasmic-override={overrides.content7}
                  className={classNames("all", sty.content7)}
                >
                  <div
                    data-plasmic-name={"form2"}
                    data-plasmic-override={overrides.form2}
                    className={classNames("all", sty.form2)}
                  >
                    <div
                      data-plasmic-name={"inputField3"}
                      data-plasmic-override={overrides.inputField3}
                      className={classNames("all", sty.inputField3)}
                    >
                      <div
                        data-plasmic-name={"inputFieldBase3"}
                        data-plasmic-override={overrides.inputFieldBase3}
                        className={classNames("all", sty.inputFieldBase3)}
                      >
                        <div
                          data-plasmic-name={"inputWithLabel3"}
                          data-plasmic-override={overrides.inputWithLabel3}
                          className={classNames("all", sty.inputWithLabel3)}
                        >
                          <div
                            data-plasmic-name={"label3"}
                            data-plasmic-override={overrides.label3}
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.label3
                            )}
                          >
                            {"Email"}
                          </div>
                          <div
                            data-plasmic-name={"input3"}
                            data-plasmic-override={overrides.input3}
                            className={classNames("all", sty.input3)}
                          >
                            <div
                              data-plasmic-name={"content8"}
                              data-plasmic-override={overrides.content8}
                              className={classNames("all", sty.content8)}
                            >
                              {false ? (
                                <Mail2Icon
                                  className={classNames("all", sty.svg__vaDbN)}
                                  role={"img"}
                                />
                              ) : null}
                              <div
                                data-plasmic-name={"text13"}
                                data-plasmic-override={overrides.text13}
                                className={classNames(
                                  "all",
                                  "__wab_text",
                                  sty.text13
                                )}
                              >
                                {"Enter your email"}
                              </div>
                            </div>
                            {false ? (
                              <div
                                data-plasmic-name={"helpIcon3"}
                                data-plasmic-override={overrides.helpIcon3}
                                className={classNames("all", sty.helpIcon3)}
                              >
                                <PlasmicImg__
                                  alt={""}
                                  className={classNames(sty.img___7TUcO)}
                                  displayHeight={"16px"}
                                  displayMaxHeight={"none"}
                                  displayMaxWidth={"100%"}
                                  displayMinHeight={"0"}
                                  displayMinWidth={"0"}
                                  displayWidth={"16px"}
                                  loading={"lazy"}
                                  src={{
                                    src: "/plasmic/tbxhub_new_landing_saas/images/helpCircle.svg",
                                    fullWidth: 16,
                                    fullHeight: 16,
                                    aspectRatio: undefined
                                  }}
                                />
                              </div>
                            ) : null}
                          </div>
                        </div>
                        {false ? (
                          <div
                            data-plasmic-name={"hintText3"}
                            data-plasmic-override={overrides.hintText3}
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.hintText3
                            )}
                          >
                            {"This is a hint text to help user."}
                          </div>
                        ) : null}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"inputField2"}
                      data-plasmic-override={overrides.inputField2}
                      className={classNames("all", sty.inputField2)}
                    >
                      <div
                        data-plasmic-name={"inputFieldBase2"}
                        data-plasmic-override={overrides.inputFieldBase2}
                        className={classNames("all", sty.inputFieldBase2)}
                      >
                        <div
                          data-plasmic-name={"inputWithLabel2"}
                          data-plasmic-override={overrides.inputWithLabel2}
                          className={classNames("all", sty.inputWithLabel2)}
                        >
                          <div
                            data-plasmic-name={"label2"}
                            data-plasmic-override={overrides.label2}
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.label2
                            )}
                          >
                            {"Password"}
                          </div>
                          <div
                            data-plasmic-name={"input2"}
                            data-plasmic-override={overrides.input2}
                            className={classNames("all", sty.input2)}
                          >
                            <div
                              data-plasmic-name={"content5"}
                              data-plasmic-override={overrides.content5}
                              className={classNames("all", sty.content5)}
                            >
                              {false ? (
                                <Mail2Icon
                                  className={classNames("all", sty.svg__zmj2Y)}
                                  role={"img"}
                                />
                              ) : null}
                              <div
                                data-plasmic-name={"text3"}
                                data-plasmic-override={overrides.text3}
                                className={classNames(
                                  "all",
                                  "__wab_text",
                                  sty.text3
                                )}
                              >
                                {
                                  "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022"
                                }
                              </div>
                            </div>
                            {false ? (
                              <div
                                data-plasmic-name={"helpIcon2"}
                                data-plasmic-override={overrides.helpIcon2}
                                className={classNames("all", sty.helpIcon2)}
                              >
                                <PlasmicImg__
                                  alt={""}
                                  className={classNames(sty.img__gfZI)}
                                  displayHeight={"16px"}
                                  displayMaxHeight={"none"}
                                  displayMaxWidth={"100%"}
                                  displayMinHeight={"0"}
                                  displayMinWidth={"0"}
                                  displayWidth={"16px"}
                                  loading={"lazy"}
                                  src={{
                                    src: "/plasmic/tbxhub_new_landing_saas/images/helpCircle.svg",
                                    fullWidth: 16,
                                    fullHeight: 16,
                                    aspectRatio: undefined
                                  }}
                                />
                              </div>
                            ) : null}
                          </div>
                        </div>
                        {false ? (
                          <div
                            data-plasmic-name={"hintText2"}
                            data-plasmic-override={overrides.hintText2}
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.hintText2
                            )}
                          >
                            {"This is a hint text to help user."}
                          </div>
                        ) : null}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"row3"}
                    data-plasmic-override={overrides.row3}
                    className={classNames("all", sty.row3)}
                  >
                    <Checkbox
                      data-plasmic-name={"checkbox"}
                      data-plasmic-override={overrides.checkbox}
                      className={classNames("__wab_instance", sty.checkbox)}
                      isSelected={generateStateValueProp($state, [
                        "checkbox",
                        "isSelected"
                      ])}
                      onChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "checkbox",
                          "isSelected"
                        ]).apply(null, eventArgs);

                        if (
                          eventArgs.length > 1 &&
                          eventArgs[1] &&
                          eventArgs[1]._plasmic_state_init_
                        ) {
                          return;
                        }
                      }}
                    />

                    <div
                      data-plasmic-name={"buttonsButton"}
                      data-plasmic-override={overrides.buttonsButton}
                      className={classNames("all", sty.buttonsButton)}
                    >
                      <div
                        data-plasmic-name={"buttonBase"}
                        data-plasmic-override={overrides.buttonBase}
                        className={classNames("all", sty.buttonBase)}
                      >
                        <div
                          data-plasmic-name={"text14"}
                          data-plasmic-override={overrides.text14}
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text14
                          )}
                        >
                          {"Forgot password"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                    color={"neutral"}
                    label={
                      <div
                        data-plasmic-name={"text"}
                        data-plasmic-override={overrides.text}
                        className={classNames("all", "__wab_text", sty.text)}
                      >
                        {"Get Started"}
                      </div>
                    }
                    size={"extraLarge"}
                  />

                  <div
                    data-plasmic-name={"actions"}
                    data-plasmic-override={overrides.actions}
                    className={classNames("all", sty.actions)}
                  >
                    <div
                      data-plasmic-name={"socialButtonGroup2"}
                      data-plasmic-override={overrides.socialButtonGroup2}
                      className={classNames("all", sty.socialButtonGroup2)}
                    >
                      <div
                        data-plasmic-name={"socialButton5"}
                        data-plasmic-override={overrides.socialButton5}
                        className={classNames("all", sty.socialButton5)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__mXIxk)}
                          displayHeight={"20px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"20px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/tbxhub_new_landing_saas/images/socialIcon.svg",
                            fullWidth: 20,
                            fullHeight: 20,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          data-plasmic-name={"text16"}
                          data-plasmic-override={overrides.text16}
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text16
                          )}
                        >
                          {"Sign in with Google"}
                        </div>
                      </div>
                      {false ? (
                        <div
                          data-plasmic-name={"socialButton6"}
                          data-plasmic-override={overrides.socialButton6}
                          className={classNames("all", sty.socialButton6)}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__gsHsU)}
                            displayHeight={"20px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/tbxhub_new_landing_saas/images/socialIcon2.svg",
                              fullWidth: 20,
                              fullHeight: 20,
                              aspectRatio: undefined
                            }}
                          />

                          <div
                            data-plasmic-name={"text17"}
                            data-plasmic-override={overrides.text17}
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.text17
                            )}
                          >
                            {"Sign in with Facebook"}
                          </div>
                        </div>
                      ) : null}
                      {false ? (
                        <div
                          data-plasmic-name={"socialButton7"}
                          data-plasmic-override={overrides.socialButton7}
                          className={classNames("all", sty.socialButton7)}
                        >
                          <SocialIcon3Icon
                            className={classNames("all", sty.svg__jJUzO)}
                            role={"img"}
                          />

                          <div
                            data-plasmic-name={"text18"}
                            data-plasmic-override={overrides.text18}
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.text18
                            )}
                          >
                            {"Sign in with Apple"}
                          </div>
                        </div>
                      ) : null}
                      {false ? (
                        <div
                          data-plasmic-name={"socialButton8"}
                          data-plasmic-override={overrides.socialButton8}
                          className={classNames("all", sty.socialButton8)}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___2WChs)}
                            displayHeight={"20px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/tbxhub_new_landing_saas/images/socialIcon4.svg",
                              fullWidth: 20,
                              fullHeight: 20,
                              aspectRatio: undefined
                            }}
                          />

                          <div
                            data-plasmic-name={"text19"}
                            data-plasmic-override={overrides.text19}
                            className={classNames(
                              "all",
                              "__wab_text",
                              sty.text19
                            )}
                          >
                            {"Sign in with X"}
                          </div>
                        </div>
                      ) : null}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"row2"}
                  data-plasmic-override={overrides.row2}
                  className={classNames("all", sty.row2)}
                >
                  <div
                    data-plasmic-name={"text20"}
                    data-plasmic-override={overrides.text20}
                    className={classNames("all", "__wab_text", sty.text20)}
                  >
                    {"Don\u2019t have an account?"}
                  </div>
                  <div
                    data-plasmic-name={"buttonsButton3"}
                    data-plasmic-override={overrides.buttonsButton3}
                    className={classNames("all", sty.buttonsButton3)}
                  >
                    <div
                      data-plasmic-name={"buttonBase3"}
                      data-plasmic-override={overrides.buttonBase3}
                      className={classNames("all", sty.buttonBase3)}
                    >
                      <div
                        data-plasmic-name={"text11"}
                        data-plasmic-override={overrides.text11}
                        className={classNames("all", "__wab_text", sty.text11)}
                      >
                        {"Sign up"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "body",
    "headerNav",
    "signUp",
    "content6",
    "header2",
    "textAndSupportingText2",
    "text12",
    "supportingText2",
    "content7",
    "form2",
    "inputField3",
    "inputFieldBase3",
    "inputWithLabel3",
    "label3",
    "input3",
    "content8",
    "text13",
    "helpIcon3",
    "hintText3",
    "inputField2",
    "inputFieldBase2",
    "inputWithLabel2",
    "label2",
    "input2",
    "content5",
    "text3",
    "helpIcon2",
    "hintText2",
    "row3",
    "checkbox",
    "buttonsButton",
    "buttonBase",
    "text14",
    "button",
    "text",
    "actions",
    "socialButtonGroup2",
    "socialButton5",
    "text16",
    "socialButton6",
    "text17",
    "socialButton7",
    "text18",
    "socialButton8",
    "text19",
    "row2",
    "text20",
    "buttonsButton3",
    "buttonBase3",
    "text11"
  ],
  body: [
    "body",
    "headerNav",
    "signUp",
    "content6",
    "header2",
    "textAndSupportingText2",
    "text12",
    "supportingText2",
    "content7",
    "form2",
    "inputField3",
    "inputFieldBase3",
    "inputWithLabel3",
    "label3",
    "input3",
    "content8",
    "text13",
    "helpIcon3",
    "hintText3",
    "inputField2",
    "inputFieldBase2",
    "inputWithLabel2",
    "label2",
    "input2",
    "content5",
    "text3",
    "helpIcon2",
    "hintText2",
    "row3",
    "checkbox",
    "buttonsButton",
    "buttonBase",
    "text14",
    "button",
    "text",
    "actions",
    "socialButtonGroup2",
    "socialButton5",
    "text16",
    "socialButton6",
    "text17",
    "socialButton7",
    "text18",
    "socialButton8",
    "text19",
    "row2",
    "text20",
    "buttonsButton3",
    "buttonBase3",
    "text11"
  ],
  headerNav: ["headerNav"],
  signUp: [
    "signUp",
    "content6",
    "header2",
    "textAndSupportingText2",
    "text12",
    "supportingText2",
    "content7",
    "form2",
    "inputField3",
    "inputFieldBase3",
    "inputWithLabel3",
    "label3",
    "input3",
    "content8",
    "text13",
    "helpIcon3",
    "hintText3",
    "inputField2",
    "inputFieldBase2",
    "inputWithLabel2",
    "label2",
    "input2",
    "content5",
    "text3",
    "helpIcon2",
    "hintText2",
    "row3",
    "checkbox",
    "buttonsButton",
    "buttonBase",
    "text14",
    "button",
    "text",
    "actions",
    "socialButtonGroup2",
    "socialButton5",
    "text16",
    "socialButton6",
    "text17",
    "socialButton7",
    "text18",
    "socialButton8",
    "text19",
    "row2",
    "text20",
    "buttonsButton3",
    "buttonBase3",
    "text11"
  ],
  content6: [
    "content6",
    "header2",
    "textAndSupportingText2",
    "text12",
    "supportingText2",
    "content7",
    "form2",
    "inputField3",
    "inputFieldBase3",
    "inputWithLabel3",
    "label3",
    "input3",
    "content8",
    "text13",
    "helpIcon3",
    "hintText3",
    "inputField2",
    "inputFieldBase2",
    "inputWithLabel2",
    "label2",
    "input2",
    "content5",
    "text3",
    "helpIcon2",
    "hintText2",
    "row3",
    "checkbox",
    "buttonsButton",
    "buttonBase",
    "text14",
    "button",
    "text",
    "actions",
    "socialButtonGroup2",
    "socialButton5",
    "text16",
    "socialButton6",
    "text17",
    "socialButton7",
    "text18",
    "socialButton8",
    "text19",
    "row2",
    "text20",
    "buttonsButton3",
    "buttonBase3",
    "text11"
  ],
  header2: ["header2", "textAndSupportingText2", "text12", "supportingText2"],
  textAndSupportingText2: [
    "textAndSupportingText2",
    "text12",
    "supportingText2"
  ],
  text12: ["text12"],
  supportingText2: ["supportingText2"],
  content7: [
    "content7",
    "form2",
    "inputField3",
    "inputFieldBase3",
    "inputWithLabel3",
    "label3",
    "input3",
    "content8",
    "text13",
    "helpIcon3",
    "hintText3",
    "inputField2",
    "inputFieldBase2",
    "inputWithLabel2",
    "label2",
    "input2",
    "content5",
    "text3",
    "helpIcon2",
    "hintText2",
    "row3",
    "checkbox",
    "buttonsButton",
    "buttonBase",
    "text14",
    "button",
    "text",
    "actions",
    "socialButtonGroup2",
    "socialButton5",
    "text16",
    "socialButton6",
    "text17",
    "socialButton7",
    "text18",
    "socialButton8",
    "text19"
  ],
  form2: [
    "form2",
    "inputField3",
    "inputFieldBase3",
    "inputWithLabel3",
    "label3",
    "input3",
    "content8",
    "text13",
    "helpIcon3",
    "hintText3",
    "inputField2",
    "inputFieldBase2",
    "inputWithLabel2",
    "label2",
    "input2",
    "content5",
    "text3",
    "helpIcon2",
    "hintText2"
  ],
  inputField3: [
    "inputField3",
    "inputFieldBase3",
    "inputWithLabel3",
    "label3",
    "input3",
    "content8",
    "text13",
    "helpIcon3",
    "hintText3"
  ],
  inputFieldBase3: [
    "inputFieldBase3",
    "inputWithLabel3",
    "label3",
    "input3",
    "content8",
    "text13",
    "helpIcon3",
    "hintText3"
  ],
  inputWithLabel3: [
    "inputWithLabel3",
    "label3",
    "input3",
    "content8",
    "text13",
    "helpIcon3"
  ],
  label3: ["label3"],
  input3: ["input3", "content8", "text13", "helpIcon3"],
  content8: ["content8", "text13"],
  text13: ["text13"],
  helpIcon3: ["helpIcon3"],
  hintText3: ["hintText3"],
  inputField2: [
    "inputField2",
    "inputFieldBase2",
    "inputWithLabel2",
    "label2",
    "input2",
    "content5",
    "text3",
    "helpIcon2",
    "hintText2"
  ],
  inputFieldBase2: [
    "inputFieldBase2",
    "inputWithLabel2",
    "label2",
    "input2",
    "content5",
    "text3",
    "helpIcon2",
    "hintText2"
  ],
  inputWithLabel2: [
    "inputWithLabel2",
    "label2",
    "input2",
    "content5",
    "text3",
    "helpIcon2"
  ],
  label2: ["label2"],
  input2: ["input2", "content5", "text3", "helpIcon2"],
  content5: ["content5", "text3"],
  text3: ["text3"],
  helpIcon2: ["helpIcon2"],
  hintText2: ["hintText2"],
  row3: ["row3", "checkbox", "buttonsButton", "buttonBase", "text14"],
  checkbox: ["checkbox"],
  buttonsButton: ["buttonsButton", "buttonBase", "text14"],
  buttonBase: ["buttonBase", "text14"],
  text14: ["text14"],
  button: ["button", "text"],
  text: ["text"],
  actions: [
    "actions",
    "socialButtonGroup2",
    "socialButton5",
    "text16",
    "socialButton6",
    "text17",
    "socialButton7",
    "text18",
    "socialButton8",
    "text19"
  ],
  socialButtonGroup2: [
    "socialButtonGroup2",
    "socialButton5",
    "text16",
    "socialButton6",
    "text17",
    "socialButton7",
    "text18",
    "socialButton8",
    "text19"
  ],
  socialButton5: ["socialButton5", "text16"],
  text16: ["text16"],
  socialButton6: ["socialButton6", "text17"],
  text17: ["text17"],
  socialButton7: ["socialButton7", "text18"],
  text18: ["text18"],
  socialButton8: ["socialButton8", "text19"],
  text19: ["text19"],
  row2: ["row2", "text20", "buttonsButton3", "buttonBase3", "text11"],
  text20: ["text20"],
  buttonsButton3: ["buttonsButton3", "buttonBase3", "text11"],
  buttonBase3: ["buttonBase3", "text11"],
  text11: ["text11"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  body: "div";
  headerNav: typeof HeaderNav;
  signUp: "div";
  content6: "div";
  header2: "div";
  textAndSupportingText2: "div";
  text12: "div";
  supportingText2: "div";
  content7: "div";
  form2: "div";
  inputField3: "div";
  inputFieldBase3: "div";
  inputWithLabel3: "div";
  label3: "div";
  input3: "div";
  content8: "div";
  text13: "div";
  helpIcon3: "div";
  hintText3: "div";
  inputField2: "div";
  inputFieldBase2: "div";
  inputWithLabel2: "div";
  label2: "div";
  input2: "div";
  content5: "div";
  text3: "div";
  helpIcon2: "div";
  hintText2: "div";
  row3: "div";
  checkbox: typeof Checkbox;
  buttonsButton: "div";
  buttonBase: "div";
  text14: "div";
  button: typeof Button;
  text: "div";
  actions: "div";
  socialButtonGroup2: "div";
  socialButton5: "div";
  text16: "div";
  socialButton6: "div";
  text17: "div";
  socialButton7: "div";
  text18: "div";
  socialButton8: "div";
  text19: "div";
  row2: "div";
  text20: "div";
  buttonsButton3: "div";
  buttonBase3: "div";
  text11: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogin__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogin__VariantsArgs;
    args?: PlasmicLogin__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogin__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogin__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogin__ArgProps,
          internalVariantPropNames: PlasmicLogin__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogin__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogin";
  } else {
    func.displayName = `PlasmicLogin.${nodeName}`;
  }
  return func;
}

export const PlasmicLogin = Object.assign(
  // Top-level PlasmicLogin renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    body: makeNodeComponent("body"),
    headerNav: makeNodeComponent("headerNav"),
    signUp: makeNodeComponent("signUp"),
    content6: makeNodeComponent("content6"),
    header2: makeNodeComponent("header2"),
    textAndSupportingText2: makeNodeComponent("textAndSupportingText2"),
    text12: makeNodeComponent("text12"),
    supportingText2: makeNodeComponent("supportingText2"),
    content7: makeNodeComponent("content7"),
    form2: makeNodeComponent("form2"),
    inputField3: makeNodeComponent("inputField3"),
    inputFieldBase3: makeNodeComponent("inputFieldBase3"),
    inputWithLabel3: makeNodeComponent("inputWithLabel3"),
    label3: makeNodeComponent("label3"),
    input3: makeNodeComponent("input3"),
    content8: makeNodeComponent("content8"),
    text13: makeNodeComponent("text13"),
    helpIcon3: makeNodeComponent("helpIcon3"),
    hintText3: makeNodeComponent("hintText3"),
    inputField2: makeNodeComponent("inputField2"),
    inputFieldBase2: makeNodeComponent("inputFieldBase2"),
    inputWithLabel2: makeNodeComponent("inputWithLabel2"),
    label2: makeNodeComponent("label2"),
    input2: makeNodeComponent("input2"),
    content5: makeNodeComponent("content5"),
    text3: makeNodeComponent("text3"),
    helpIcon2: makeNodeComponent("helpIcon2"),
    hintText2: makeNodeComponent("hintText2"),
    row3: makeNodeComponent("row3"),
    checkbox: makeNodeComponent("checkbox"),
    buttonsButton: makeNodeComponent("buttonsButton"),
    buttonBase: makeNodeComponent("buttonBase"),
    text14: makeNodeComponent("text14"),
    button: makeNodeComponent("button"),
    text: makeNodeComponent("text"),
    actions: makeNodeComponent("actions"),
    socialButtonGroup2: makeNodeComponent("socialButtonGroup2"),
    socialButton5: makeNodeComponent("socialButton5"),
    text16: makeNodeComponent("text16"),
    socialButton6: makeNodeComponent("socialButton6"),
    text17: makeNodeComponent("text17"),
    socialButton7: makeNodeComponent("socialButton7"),
    text18: makeNodeComponent("text18"),
    socialButton8: makeNodeComponent("socialButton8"),
    text19: makeNodeComponent("text19"),
    row2: makeNodeComponent("row2"),
    text20: makeNodeComponent("text20"),
    buttonsButton3: makeNodeComponent("buttonsButton3"),
    buttonBase3: makeNodeComponent("buttonBase3"),
    text11: makeNodeComponent("text11"),

    // Metadata about props expected for PlasmicLogin
    internalVariantProps: PlasmicLogin__VariantProps,
    internalArgProps: PlasmicLogin__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/login",
      pagePath: "/login",
      params: {},
      query: {}
    })
  }
);

export default PlasmicLogin;
/* prettier-ignore-end */
