/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uAEPi88t4b3bpYVaXpTdTs
// Component: Idw-fO8O8e-A

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uAEPi88t4b3bpYVaXpTdTs/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uAEPi88t4b3bpYVaXpTdTs/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicFooter.module.css"; // plasmic-import: Idw-fO8O8e-A/css

import HorizontalLogo22SvgIcon from "./icons/PlasmicIcon__HorizontalLogo22Svg"; // plasmic-import: FYLniLePjA4H/icon

createPlasmicElementProxy;

export type PlasmicFooter__VariantMembers = {};
export type PlasmicFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooter__VariantsArgs;
export const PlasmicFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicFooter__ArgsType = {};
type ArgPropType = keyof PlasmicFooter__ArgsType;
export const PlasmicFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicFooter__OverridesType = {
  footer?: Flex__<"div">;
  child4?: Flex__<"div">;
  frame50?: Flex__<"div">;
  svg?: Flex__<"svg">;
  autoLayoutHorizontal27?: Flex__<"div">;
  autoLayoutHorizontal28?: Flex__<"div">;
  autoLayoutVertical19?: Flex__<"div">;
  autoLayoutVertical20?: Flex__<"div">;
  autoLayoutHorizontal29?: Flex__<"div">;
  autoLayoutHorizontal30?: Flex__<"div">;
  autoLayoutHorizontal31?: Flex__<"div">;
  autoLayoutHorizontal32?: Flex__<"div">;
  autoLayoutVertical21?: Flex__<"div">;
  autoLayoutVertical22?: Flex__<"div">;
  autoLayoutHorizontal33?: Flex__<"div">;
  autoLayoutHorizontal34?: Flex__<"div">;
  autoLayoutHorizontal35?: Flex__<"div">;
  autoLayoutVertical23?: Flex__<"div">;
  autoLayoutVertical24?: Flex__<"div">;
  autoLayoutHorizontal36?: Flex__<"div">;
  autoLayoutHorizontal37?: Flex__<"div">;
  autoLayoutHorizontal38?: Flex__<"div">;
  autoLayoutVertical25?: Flex__<"div">;
  autoLayoutVertical26?: Flex__<"div">;
  autoLayoutHorizontal39?: Flex__<"div">;
  autoLayoutHorizontal40?: Flex__<"div">;
  autoLayoutHorizontal41?: Flex__<"div">;
  child5?: Flex__<"div">;
};

export interface DefaultFooterProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooter__RenderFunc(props: {
  variants: PlasmicFooter__VariantsArgs;
  args: PlasmicFooter__ArgsType;
  overrides: PlasmicFooter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"footer"}
      data-plasmic-override={overrides.footer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_uAEPi88t4b3bpYVaXpTdTs",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.footer
      )}
    >
      <div
        data-plasmic-name={"child4"}
        data-plasmic-override={overrides.child4}
        className={classNames("all", sty.child4)}
      >
        <div
          data-plasmic-name={"frame50"}
          data-plasmic-override={overrides.frame50}
          className={classNames("all", sty.frame50)}
        >
          <HorizontalLogo22SvgIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames("all", sty.svg)}
            role={"img"}
          />
        </div>
        <div
          data-plasmic-name={"autoLayoutHorizontal27"}
          data-plasmic-override={overrides.autoLayoutHorizontal27}
          className={classNames("all", sty.autoLayoutHorizontal27)}
        >
          <div
            data-plasmic-name={"autoLayoutHorizontal28"}
            data-plasmic-override={overrides.autoLayoutHorizontal28}
            className={classNames("all", sty.autoLayoutHorizontal28)}
          >
            <div
              data-plasmic-name={"autoLayoutVertical19"}
              data-plasmic-override={overrides.autoLayoutVertical19}
              className={classNames("all", sty.autoLayoutVertical19)}
            >
              <div className={classNames("all", "__wab_text", sty.text__xuaNo)}>
                {"Product"}
              </div>
              <div
                data-plasmic-name={"autoLayoutVertical20"}
                data-plasmic-override={overrides.autoLayoutVertical20}
                className={classNames("all", sty.autoLayoutVertical20)}
              >
                <div
                  data-plasmic-name={"autoLayoutHorizontal29"}
                  data-plasmic-override={overrides.autoLayoutHorizontal29}
                  className={classNames("all", sty.autoLayoutHorizontal29)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__pd58N)}
                  >
                    {"Features"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"autoLayoutHorizontal30"}
                  data-plasmic-override={overrides.autoLayoutHorizontal30}
                  className={classNames("all", sty.autoLayoutHorizontal30)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__xAu1X)}
                  >
                    {"Pricing"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"autoLayoutHorizontal31"}
                  data-plasmic-override={overrides.autoLayoutHorizontal31}
                  className={classNames("all", sty.autoLayoutHorizontal31)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__cJBlK)}
                  >
                    {"Changelog"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"autoLayoutHorizontal32"}
                  data-plasmic-override={overrides.autoLayoutHorizontal32}
                  className={classNames("all", sty.autoLayoutHorizontal32)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__pbr5Z)}
                  >
                    {"Support"}
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"autoLayoutVertical21"}
              data-plasmic-override={overrides.autoLayoutVertical21}
              className={classNames("all", sty.autoLayoutVertical21)}
            >
              <div className={classNames("all", "__wab_text", sty.text__yq1U)}>
                {"Legal"}
              </div>
              <div
                data-plasmic-name={"autoLayoutVertical22"}
                data-plasmic-override={overrides.autoLayoutVertical22}
                className={classNames("all", sty.autoLayoutVertical22)}
              >
                <div
                  data-plasmic-name={"autoLayoutHorizontal33"}
                  data-plasmic-override={overrides.autoLayoutHorizontal33}
                  className={classNames("all", sty.autoLayoutHorizontal33)}
                >
                  <div
                    className={classNames(
                      "all",
                      "__wab_text",
                      sty.text___6O04X
                    )}
                  >
                    {"Terms of Privacy"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"autoLayoutHorizontal34"}
                  data-plasmic-override={overrides.autoLayoutHorizontal34}
                  className={classNames("all", sty.autoLayoutHorizontal34)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__ey5UO)}
                  >
                    {"Privacy Policy"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"autoLayoutHorizontal35"}
                  data-plasmic-override={overrides.autoLayoutHorizontal35}
                  className={classNames("all", sty.autoLayoutHorizontal35)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__cqzBp)}
                  >
                    {"Security"}
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"autoLayoutVertical23"}
              data-plasmic-override={overrides.autoLayoutVertical23}
              className={classNames("all", sty.autoLayoutVertical23)}
            >
              <div className={classNames("all", "__wab_text", sty.text__jWryq)}>
                {"Company"}
              </div>
              <div
                data-plasmic-name={"autoLayoutVertical24"}
                data-plasmic-override={overrides.autoLayoutVertical24}
                className={classNames("all", sty.autoLayoutVertical24)}
              >
                <div
                  data-plasmic-name={"autoLayoutHorizontal36"}
                  data-plasmic-override={overrides.autoLayoutHorizontal36}
                  className={classNames("all", sty.autoLayoutHorizontal36)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__phBya)}
                  >
                    {"Blog"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"autoLayoutHorizontal37"}
                  data-plasmic-override={overrides.autoLayoutHorizontal37}
                  className={classNames("all", sty.autoLayoutHorizontal37)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__dddJx)}
                  >
                    {"Contact"}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"autoLayoutHorizontal38"}
            data-plasmic-override={overrides.autoLayoutHorizontal38}
            className={classNames("all", sty.autoLayoutHorizontal38)}
          >
            <div
              data-plasmic-name={"autoLayoutVertical25"}
              data-plasmic-override={overrides.autoLayoutVertical25}
              className={classNames("all", sty.autoLayoutVertical25)}
            >
              <div className={classNames("all", "__wab_text", sty.text__sl0Aj)}>
                {"Social"}
              </div>
              <div
                data-plasmic-name={"autoLayoutVertical26"}
                data-plasmic-override={overrides.autoLayoutVertical26}
                className={classNames("all", sty.autoLayoutVertical26)}
              >
                <div
                  data-plasmic-name={"autoLayoutHorizontal39"}
                  data-plasmic-override={overrides.autoLayoutHorizontal39}
                  className={classNames("all", sty.autoLayoutHorizontal39)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__hvdk)}
                  >
                    {"Dribbble"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"autoLayoutHorizontal40"}
                  data-plasmic-override={overrides.autoLayoutHorizontal40}
                  className={classNames("all", sty.autoLayoutHorizontal40)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__bgUjB)}
                  >
                    {"Behance"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"autoLayoutHorizontal41"}
                  data-plasmic-override={overrides.autoLayoutHorizontal41}
                  className={classNames("all", sty.autoLayoutHorizontal41)}
                >
                  <div
                    className={classNames("all", "__wab_text", sty.text__fzY5B)}
                  >
                    {"Discord"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        data-plasmic-name={"child5"}
        data-plasmic-override={overrides.child5}
        className={classNames("all", sty.child5)}
      >
        <div className={classNames("all", "__wab_text", sty.text__dce1B)}>
          {"All rights reserved.\u00a9 2026 DANG designs"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  footer: [
    "footer",
    "child4",
    "frame50",
    "svg",
    "autoLayoutHorizontal27",
    "autoLayoutHorizontal28",
    "autoLayoutVertical19",
    "autoLayoutVertical20",
    "autoLayoutHorizontal29",
    "autoLayoutHorizontal30",
    "autoLayoutHorizontal31",
    "autoLayoutHorizontal32",
    "autoLayoutVertical21",
    "autoLayoutVertical22",
    "autoLayoutHorizontal33",
    "autoLayoutHorizontal34",
    "autoLayoutHorizontal35",
    "autoLayoutVertical23",
    "autoLayoutVertical24",
    "autoLayoutHorizontal36",
    "autoLayoutHorizontal37",
    "autoLayoutHorizontal38",
    "autoLayoutVertical25",
    "autoLayoutVertical26",
    "autoLayoutHorizontal39",
    "autoLayoutHorizontal40",
    "autoLayoutHorizontal41",
    "child5"
  ],
  child4: [
    "child4",
    "frame50",
    "svg",
    "autoLayoutHorizontal27",
    "autoLayoutHorizontal28",
    "autoLayoutVertical19",
    "autoLayoutVertical20",
    "autoLayoutHorizontal29",
    "autoLayoutHorizontal30",
    "autoLayoutHorizontal31",
    "autoLayoutHorizontal32",
    "autoLayoutVertical21",
    "autoLayoutVertical22",
    "autoLayoutHorizontal33",
    "autoLayoutHorizontal34",
    "autoLayoutHorizontal35",
    "autoLayoutVertical23",
    "autoLayoutVertical24",
    "autoLayoutHorizontal36",
    "autoLayoutHorizontal37",
    "autoLayoutHorizontal38",
    "autoLayoutVertical25",
    "autoLayoutVertical26",
    "autoLayoutHorizontal39",
    "autoLayoutHorizontal40",
    "autoLayoutHorizontal41"
  ],
  frame50: ["frame50", "svg"],
  svg: ["svg"],
  autoLayoutHorizontal27: [
    "autoLayoutHorizontal27",
    "autoLayoutHorizontal28",
    "autoLayoutVertical19",
    "autoLayoutVertical20",
    "autoLayoutHorizontal29",
    "autoLayoutHorizontal30",
    "autoLayoutHorizontal31",
    "autoLayoutHorizontal32",
    "autoLayoutVertical21",
    "autoLayoutVertical22",
    "autoLayoutHorizontal33",
    "autoLayoutHorizontal34",
    "autoLayoutHorizontal35",
    "autoLayoutVertical23",
    "autoLayoutVertical24",
    "autoLayoutHorizontal36",
    "autoLayoutHorizontal37",
    "autoLayoutHorizontal38",
    "autoLayoutVertical25",
    "autoLayoutVertical26",
    "autoLayoutHorizontal39",
    "autoLayoutHorizontal40",
    "autoLayoutHorizontal41"
  ],
  autoLayoutHorizontal28: [
    "autoLayoutHorizontal28",
    "autoLayoutVertical19",
    "autoLayoutVertical20",
    "autoLayoutHorizontal29",
    "autoLayoutHorizontal30",
    "autoLayoutHorizontal31",
    "autoLayoutHorizontal32",
    "autoLayoutVertical21",
    "autoLayoutVertical22",
    "autoLayoutHorizontal33",
    "autoLayoutHorizontal34",
    "autoLayoutHorizontal35",
    "autoLayoutVertical23",
    "autoLayoutVertical24",
    "autoLayoutHorizontal36",
    "autoLayoutHorizontal37"
  ],
  autoLayoutVertical19: [
    "autoLayoutVertical19",
    "autoLayoutVertical20",
    "autoLayoutHorizontal29",
    "autoLayoutHorizontal30",
    "autoLayoutHorizontal31",
    "autoLayoutHorizontal32"
  ],
  autoLayoutVertical20: [
    "autoLayoutVertical20",
    "autoLayoutHorizontal29",
    "autoLayoutHorizontal30",
    "autoLayoutHorizontal31",
    "autoLayoutHorizontal32"
  ],
  autoLayoutHorizontal29: ["autoLayoutHorizontal29"],
  autoLayoutHorizontal30: ["autoLayoutHorizontal30"],
  autoLayoutHorizontal31: ["autoLayoutHorizontal31"],
  autoLayoutHorizontal32: ["autoLayoutHorizontal32"],
  autoLayoutVertical21: [
    "autoLayoutVertical21",
    "autoLayoutVertical22",
    "autoLayoutHorizontal33",
    "autoLayoutHorizontal34",
    "autoLayoutHorizontal35"
  ],
  autoLayoutVertical22: [
    "autoLayoutVertical22",
    "autoLayoutHorizontal33",
    "autoLayoutHorizontal34",
    "autoLayoutHorizontal35"
  ],
  autoLayoutHorizontal33: ["autoLayoutHorizontal33"],
  autoLayoutHorizontal34: ["autoLayoutHorizontal34"],
  autoLayoutHorizontal35: ["autoLayoutHorizontal35"],
  autoLayoutVertical23: [
    "autoLayoutVertical23",
    "autoLayoutVertical24",
    "autoLayoutHorizontal36",
    "autoLayoutHorizontal37"
  ],
  autoLayoutVertical24: [
    "autoLayoutVertical24",
    "autoLayoutHorizontal36",
    "autoLayoutHorizontal37"
  ],
  autoLayoutHorizontal36: ["autoLayoutHorizontal36"],
  autoLayoutHorizontal37: ["autoLayoutHorizontal37"],
  autoLayoutHorizontal38: [
    "autoLayoutHorizontal38",
    "autoLayoutVertical25",
    "autoLayoutVertical26",
    "autoLayoutHorizontal39",
    "autoLayoutHorizontal40",
    "autoLayoutHorizontal41"
  ],
  autoLayoutVertical25: [
    "autoLayoutVertical25",
    "autoLayoutVertical26",
    "autoLayoutHorizontal39",
    "autoLayoutHorizontal40",
    "autoLayoutHorizontal41"
  ],
  autoLayoutVertical26: [
    "autoLayoutVertical26",
    "autoLayoutHorizontal39",
    "autoLayoutHorizontal40",
    "autoLayoutHorizontal41"
  ],
  autoLayoutHorizontal39: ["autoLayoutHorizontal39"],
  autoLayoutHorizontal40: ["autoLayoutHorizontal40"],
  autoLayoutHorizontal41: ["autoLayoutHorizontal41"],
  child5: ["child5"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  footer: "div";
  child4: "div";
  frame50: "div";
  svg: "svg";
  autoLayoutHorizontal27: "div";
  autoLayoutHorizontal28: "div";
  autoLayoutVertical19: "div";
  autoLayoutVertical20: "div";
  autoLayoutHorizontal29: "div";
  autoLayoutHorizontal30: "div";
  autoLayoutHorizontal31: "div";
  autoLayoutHorizontal32: "div";
  autoLayoutVertical21: "div";
  autoLayoutVertical22: "div";
  autoLayoutHorizontal33: "div";
  autoLayoutHorizontal34: "div";
  autoLayoutHorizontal35: "div";
  autoLayoutVertical23: "div";
  autoLayoutVertical24: "div";
  autoLayoutHorizontal36: "div";
  autoLayoutHorizontal37: "div";
  autoLayoutHorizontal38: "div";
  autoLayoutVertical25: "div";
  autoLayoutVertical26: "div";
  autoLayoutHorizontal39: "div";
  autoLayoutHorizontal40: "div";
  autoLayoutHorizontal41: "div";
  child5: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooter__VariantsArgs;
    args?: PlasmicFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFooter__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooter__ArgProps,
          internalVariantPropNames: PlasmicFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "footer") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("footer"),
  {
    // Helper components rendering sub-elements
    child4: makeNodeComponent("child4"),
    frame50: makeNodeComponent("frame50"),
    svg: makeNodeComponent("svg"),
    autoLayoutHorizontal27: makeNodeComponent("autoLayoutHorizontal27"),
    autoLayoutHorizontal28: makeNodeComponent("autoLayoutHorizontal28"),
    autoLayoutVertical19: makeNodeComponent("autoLayoutVertical19"),
    autoLayoutVertical20: makeNodeComponent("autoLayoutVertical20"),
    autoLayoutHorizontal29: makeNodeComponent("autoLayoutHorizontal29"),
    autoLayoutHorizontal30: makeNodeComponent("autoLayoutHorizontal30"),
    autoLayoutHorizontal31: makeNodeComponent("autoLayoutHorizontal31"),
    autoLayoutHorizontal32: makeNodeComponent("autoLayoutHorizontal32"),
    autoLayoutVertical21: makeNodeComponent("autoLayoutVertical21"),
    autoLayoutVertical22: makeNodeComponent("autoLayoutVertical22"),
    autoLayoutHorizontal33: makeNodeComponent("autoLayoutHorizontal33"),
    autoLayoutHorizontal34: makeNodeComponent("autoLayoutHorizontal34"),
    autoLayoutHorizontal35: makeNodeComponent("autoLayoutHorizontal35"),
    autoLayoutVertical23: makeNodeComponent("autoLayoutVertical23"),
    autoLayoutVertical24: makeNodeComponent("autoLayoutVertical24"),
    autoLayoutHorizontal36: makeNodeComponent("autoLayoutHorizontal36"),
    autoLayoutHorizontal37: makeNodeComponent("autoLayoutHorizontal37"),
    autoLayoutHorizontal38: makeNodeComponent("autoLayoutHorizontal38"),
    autoLayoutVertical25: makeNodeComponent("autoLayoutVertical25"),
    autoLayoutVertical26: makeNodeComponent("autoLayoutVertical26"),
    autoLayoutHorizontal39: makeNodeComponent("autoLayoutHorizontal39"),
    autoLayoutHorizontal40: makeNodeComponent("autoLayoutHorizontal40"),
    autoLayoutHorizontal41: makeNodeComponent("autoLayoutHorizontal41"),
    child5: makeNodeComponent("child5"),

    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
